# copy to .streamlit/secrets.toml and never commit

GEMINI_KEY = 'AIzaSyAzu...'

[connections.neon]
url = 'postgresql://neondb_owner:z4TVPUS0YmBs@ep-steep-feather-a5pyyudd.us-east-2.aws.neon.tech/neondb?sslmode=require&options=-c search_path=hackomate'
